version: "3"
services:
  user:
    image: ztj1993/mysql-tools:0.0.1
    command: adduser % user 123456
    network_mode: custom
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456

  db:
    image: ztj1993/mysql-tools:0.0.1
    command: create database user_db
    network_mode: custom
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    depends_on:
      - user
