version: "3"
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    hostname: spark-master
    container_name: spark-master
    network_mode: custom
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080/tcp
      - 7077/tcp
    ports:
      - 8080/tcp
      - 7077/tcp

  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    hostname: spark-worker
    container_name: spark-worker
    network_mode: custom
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8081/tcp

  spark-submit:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-submit
    hostname: spark-submit
    container_name: spark-submit
    network_mode: custom
    tty: true
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/spark-script:/srv/spark-script:rw
