version: "3"
services:

  elasticsearch:
    image: elasticsearch:7.8.0
    hostname: elasticsearch
    container_name: elasticsearch
    network_mode: custom
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-credentials=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - elasticsearch:/usr/share/elasticsearch/data:rw
    expose:
      - 9200/tcp
      - 9300/tcp
    ports:
      - 9200/tcp
      - 9300/tcp

volumes:
  elasticsearch:
    driver: local
