version: "3"
services:

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-7.8.0}
    hostname: ${ELASTICSEARCH_HOSTNAME:-elasticsearch}
    container_name: ${ELASTICSEARCH_CONTAINER_NAME:-elasticsearch}
    network_mode: custom
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - elasticsearch:/usr/share/elasticsearch/data:rw
    expose:
      - 9200/tcp
      - 9300/tcp
    ports:
      - 9200/tcp
      - 9300/tcp

volumes:
  elasticsearch:
    driver: local
