version: "3"
services:

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    network_mode: custom
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080/tcp
