version: "3"
services:

  mysql:
    image: mysql:5.7
    command: >
      mysqld
      --default-authentication-plugin=mysql_native_password
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server_id=1
    hostname: mysql
    container_name: mysql
    network_mode: custom
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql:/var/lib/mysql:rw
    expose:
      - 3306/tcp
      - 33060/tcp

volumes:
  mysql:
    driver: local
