version: "3"
services:
  postgre:
    image: postgres:12.3
    hostname: ${POSTGRES_HOSTNAME:-postgres}
    container_name: ${POSTGRES_HOSTNAME:-postgres}
    network_mode: custom
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres:/var/lib/postgresql/data:rw
    expose:
      - 5432/tcp

volumes:
  postgres:
    driver: local
