version: "3"
services:

  redis:
    image: redis:6.0.6
    command:  >
      redis-server
      --appendonly yes
      --requirepass 123456
    hostname: redis
    container_name: redis
    network_mode: custom
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis:/data:rw
    expose:
      - 6379/tcp

volumes:
  redis:
    driver: local
